name: compile Rust server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            release_suffix: ubuntu
          - os: windows-latest
            release_suffix: windows

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
        cargo build --verbose
        cp target/debug/vnfind* .
    - name: Run tests
      run: cargo test --verbose
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vnfind_${{ matrix.release_suffix }}
        path: |
          vnfind
          vnfind.exe
          www
